### ISSUE TITLE
Can not craft anything

### ISSUE THREAD

**Issue by IvyKirkland** [Zelioth/Friends-United#2]
I can not craft anything. I tried  in the  2 by 2 and in a crafting grid
![2023-03-22_12 12 59](https://user-images.githubusercontent.com/98922486/227007346-6307bc78-64e1-443a-9601-15764005a173.png)
![2023-03-22_12 23 59](https://user-images.githubusercontent.com/98922486/227007367-5e1fb77f-dddf-41b5-941e-ebe555da17e8.png)
![2023-03-22_12 27 27](https://user-images.githubusercontent.com/98922486/227007380-8766ef61-9527-4918-97c5-82fcf0b14d85.png)

**Comment by Zelioth** [comment]
Issue was related to KubeJS for some odd reason. Issue is fixed in later versions.
